name: ci-mac
on:   [push]
jobs:
    ci:
        strategy:
            matrix:
                run-config:
                    - { scheme: 'SpacesInfo', configuration: 'Debug',   project: 'SpacesInfo.xcodeproj', build: 1, analyze: 1, test: 0, info: 1, destination: 'platform=macOS' }
                    - { scheme: 'SpacesInfo', configuration: 'Release', project: 'SpacesInfo.xcodeproj', build: 1, analyze: 1, test: 0, info: 1, destination: 'platform=macOS' }
        steps:
            
            - uses: actions/checkout@v1
              with:
                submodules: 'recursive'
                
            - uses: macmade/action-xcodebuild@v1.0.0
